import UserProfile from '@/component/Profile';
import { userSession } from '@/lib/session';
import React from 'react';
export const metadata = {
    title: "P-Hub | Admin Profile",
    description: "Generated by create next app",
};
const AdminProfile = async () => {
    const user = await userSession()
    return (
        <div>
            <UserProfile user={user}></UserProfile>
        </div>
    );
};

export default AdminProfile;